name: Update

on:
  push:
    branches:
      - x
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: You are a
      run: echo legend

